In [1]:
import numpy as np
from scipy import stats

In [2]:
x = [10, 2, 2, 5, 26, 6]

In [13]:
# Выборочное среднее
mean = np.mean(x)
print(f'Среднее значение массива x: {mean} ')

Среднее значение массива x: 8.5

In [14]:
# ИЛИ 
mean = sum(x) / len(x)
mean

8.5

In [15]:
# выборочное среднее сильно чувствительно к выбросам
y = [10, 2, 2, 5, 26, 6, 500]
mean = np.mean(y)
print(f'Среднее значение массива y: {mean} ')

Среднее значение массива y: 78.71428571428571

In [17]:
# усеченое среднее
stats.trim_mean(y, 0.2)
print(f'Усеченое cреднее значение массива y: {stats.trim_mean(y, 0.2)} ')

Усеченое cреднее значение массива y: 9.8

In [23]:
# взвешенное среднее
y = np.array([10, 2, 2, 5, 26, 6, 500])
w = np.array([0.2, 0.5, 0.5, 0.4, 0.2, 0.3, 0.1])

wm = y.dot(w) / sum(w)
wm

np.float64(28.636363636363633)

In [ ]:
# или
wm = np.average(y, weights=w)
wm

np.float64(28.636363636363633)

In [25]:
# медиана
y = [10, 2, 2, 5, 26, 6, 500]

sorted(y)

[2, 2, 5, 6, 10, 26, 500]

In [ ]:
# медиана должна быть 6
median = np.median(y)
print(f'Медиана массива y: {median} ')

Медиана массива y: 6.0

In [30]:
# медиана для четного количества элементов
x = [10, 2, 2, 5, 26, 6]
median = np.median(x)
print(sorted(x))
print(f'Медиана массива x: {median} ')

[2, 2, 5, 6, 10, 26]
Медиана массива x: 5.5

In [34]:
# мода 
x = [10, 2, 2, 5, 26, 6]

mode = stats.mode(x)
print(f'Мода массива x: {mode} ')

Мода массива x: ModeResult(mode=np.int64(2), count=np.int64(2))

In [35]:
# для бинарных значений
b = [0, 1, 0, 1, 0]
mode = stats.mode(b)
print(f'Мода массива b: {mode} ')

Мода массива b: ModeResult(mode=np.int64(0), count=np.int64(3))

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('datas/data.csv')
data.head(2)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94

In [42]:
data.describe()

            Row ID   Postal Code         Sales
count  9800.000000   9789.000000   9800.000000
mean   4900.500000  55273.322403    230.769059
std    2829.160653  32041.223413    626.651875
min       1.000000   1040.000000      0.444000
25%    2450.750000  23223.000000     17.248000
50%    4900.500000  58103.000000     54.490000
75%    7350.250000  90008.000000    210.605000
max    9800.000000  99301.000000  22638.480000

In [44]:
mean = np.mean(data.Sales)
mean

np.float64(230.76905945918367)

In [46]:
data.Sales.mean()

np.float64(230.76905945918367)

In [47]:
# усеченое среднее
len(data.Sales)

9800

In [49]:
len(data.Sales) * 0.1 * 2

1960.0

In [50]:
len(data.Sales) * 0.01 * 2

196.0

In [51]:
stats.trim_mean(data.Sales, 0.01), stats.trim_mean(data.Sales, 0.1)

(np.float64(188.935317544773), np.float64(113.65588941326531))

In [53]:
# медиана
median = np.median(data.Sales)
median

np.float64(54.489999999999995)

In [54]:
data.Sales.median()

np.float64(54.489999999999995)

In [55]:
# мода
data.State.mode()

0    California
Name: State, dtype: str

In [58]:
len(data[data.State == 'California'])

1946